services:
  kinopoikdb.api:
    image: ${DOCKER_REGISTRY-}kinopoikdbapi
    build:
      context: .
      dockerfile: src/KinopoikDB.Api/Dockerfile
    depends_on: 
      - postgres
  
  postgres:
    container_name: "postgreSQL"
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
volumes:
  postgres_data:

