services:
  kinopoikdb.api:
    image: ${DOCKER_REGISTRY-}kinopoikdbapi
    build:
      context: .
      dockerfile: src/KinopoikDB.Api/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
        ConnectionStrings__DefaultConnection: ${POSTGRES_CONNECTION}
        ConnectionStrings__Redis: ${REDIS_CONNECTION}
        KinopoiskSettings__ApiKey: ${APIKEY}
    depends_on: 
      - postgres
      - redis
    networks:
      - mynetwork
  
  redis:
    container_name: "redis"
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  postgres:
    container_name: "postgreSQL"
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks:
      - mynetwork
volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge

